domains:
- domain: app.bigseat.co
  type: PRIMARY
name: app
region: ams
static_sites:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: bigseat-co/app
  name: app
  routes:
  - path: /